import = [
    "~/.config/alacritty/themes/tokyonight-storm.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 13.5

# Default colors
[colors.primary]
background = '#24283b'
foreground = '#a9b1d6'

