import = ["~/.config/alacritty/themes/tokyonight-moon.toml"]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
option_as_alt = "Both"
dynamic_padding = false

[font]
normal.family = "MesloLGL Nerd Font Mono"

size = 13

